abrigo_animal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('site_abrigo.urls')),
    path('', include('app_usuarios.urls', namespace = 'app_usuarios')),
    path('admin/', admin.site.urls),
]

app_usuarios/urls.py
from django.urls import path
from django.conf import settings

from .views import *

app_name = 'app_usuarios'

urlpatterns = [
    path("cadastro_pessoa/", cadastro_pessoa, name="cadastro_pessoa"),
 
]

site_abrigo/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("lista_animais/", views.lista_animais, name="lista_animais"),
    path('animal/<int:animal_id>/', views.detalhe_animal, name='detalhe_animal'),
    path("cadastro_animal/", views.cadastro_animal, name="cadastro_animal"),
    path("pesquisar_animais/", views.pesquisar_animais, name="pesquisar_animais"),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_abrigo/models.py
from django.db import models
import os
from django.conf import settings
from django.utils import timezone


def upload_to_image(instance, filename):
    # Verificar se a instância é do tipo CadastroAnimal
    if isinstance(instance, CadastroAnimal):
        # Verificar se a instância já foi salva e tem um ID
        if instance.id:
            # Formatar o caminho com ID e nome em minúsculo
            return os.path.join('galeria', instance.nome.lower(), f'{instance.id}_{instance.nome.lower()}_{filename}')
        else:
            # Caso o ID ainda não esteja disponível, salvar apenas com o nome
            return os.path.join('galeria', instance.nome.lower(), filename)
    
    # Verificar se a instância é do tipo GaleriaAnimal (relacionada ao CadastroAnimal)
    elif hasattr(instance, 'animal') and isinstance(instance.animal, CadastroAnimal):
        # Se o ID do animal está disponível
        if instance.animal.id:
            return os.path.join('galeria', instance.animal.nome.lower(), f'{instance.animal.id}_{instance.animal.nome.lower()}_{filename}')
        else:
            return os.path.join('galeria', instance.animal.nome.lower(), filename)
    
    return os.path.join('galeria', 'default', filename)



class CadastroAnimal(models.Model):
    SEXO_CHOICES = [
        ('macho', 'Macho'),
        ('fêmea', 'Fêmea'),
    ]
    ESPECIE_CHOICES = [
        ('cachorro', 'Cachorro'),
        ('gato', 'Gato'),
    ]

    nome = models.CharField(max_length=75,blank=False, null=False)
    idade = models.PositiveIntegerField(blank=False, null=False)
    raca = models.CharField(max_length=75, default='Viralata', blank=False, null=False)
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES, default='macho')
    especie = models.CharField(max_length=10, choices=ESPECIE_CHOICES, default='cachorro')
    disponivel = models.BooleanField(default=True)
    historico_saude = models.TextField(max_length=300, blank=False, null=False)
    data_criacao = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = 'Cadastro de Animal'
        verbose_name_plural = 'Cadastro de Animais'
        ordering = ['nome']

    def __str__(self):
        return self.nome.upper()


class GaleriaAnimal(models.Model):
    animal = models.ForeignKey(CadastroAnimal, on_delete=models.CASCADE, related_name='galeria')
    imagem = models.ImageField(upload_to=upload_to_image, blank=True, null=True)


    def __str__(self):
        return f'Imagem de {self.animal.nome}'

site_abrigo/forms.py
'''
Classe do formulario => define quais campos vamos validar.
Field => campo do formulário, isto é, qual é o tipo do campo (senha, e-mail, nome, etc).
Widget => como o campo vai ser representado em HTML (input, text area, etc.)
'''
from django import forms

from .models  import CadastroAnimal

class FormCadastroAnimal(forms.ModelForm):
    class Meta:
        model = CadastroAnimal
        fields = ['nome', 'idade', 'raca', 'sexo', 'especie', 'historico_saude']
        exclude = ['data_criacao', 'disponivel']

        def __init__(self, *args, **kwargs):
            super(CadastroAnimal, self).__init__(*args, **kwargs)
            self.fields['nome'].widget.attrs.update({'placeholder': 'Nome do bichinho'})
            self.fields['idade'].widget.attrs.update({'placeholder': 'Digite a idade'})
            self.fields['historico_saude'].widget.attrs.update({'placeholder': 'Digite o historico de saude do animal'})
            self.fields['raca'].empty_label = "Selecione a raça" 
            self.fields['sexo'].empty_label = "Selecione o sexo" 
            self.fields['especie'].empty_label = "Selecione a espécie" 

site_abrigo/views.py
from django.shortcuts import render, redirect,  get_object_or_404
from django.http import HttpResponse
from django.core.files.base import ContentFile
from django.utils import timezone
from django.db.models import Q
import os
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from .forms import FormCadastroAnimal
from .models import GaleriaAnimal, CadastroAnimal


def home(request):
    # Buscar todos os animais cadastrados no banco de dados
    animais = CadastroAnimal.objects.all()
    
    # Renderizar o template com a lista de animais
    return render(request, 'home.html', context={'animais': animais})


def lista_animais(request):
    # Buscar todos os animais cadastrados no banco de dados disponivel para adoção
    animais = CadastroAnimal.objects.filter(disponivel_para_adocao = True)

    # animais = CadastroAnimal.objects.all()

    # Renderizar o template com a lista de animais
    return render(request, 'lista_animais.html', context={'animais': animais})


def pesquisar_animais(request):
    if 'pesquisa_query' in request.GET:
        pesquisa_query = request.GET['pesquisa_query']

        #fazendo pessquisa com multiplas palavra chaves e campos
        query_clean = Q(Q(nome___unaccent__icontains = pesquisa_query) | Q(raca___unaccent__icontains = pesquisa_query))

        animais = CadastroAnimal.objects.filter(query_clean)

        #fazendo pesquisa só de um campo
        # animais = CadastroAnimal.objects.filter(nome__icontains = pesquisa_query)
        
        return render(request, 'pesquisar_animais.html', {'pesquisa_query':pesquisa_query , 'animais': animais})
    
    else:
        return render(request, 'pesquisar_animais.html', {})



def detalhe_animal(request, animal_id):
    animal = get_object_or_404(CadastroAnimal, id=animal_id)

    # Supondo que você queira exibir todas as imagem na pasta do animal
    imagem = []
    if animal.imagem:
        # Aqui, a URL das imagem deve ser construída com base na pasta do animal
        imagem.append(animal.imagem.url)  # Adiciona a imagem principal
        # Caso tenha outras imagem em subpastas, você pode listar as imagem que deseja
        # Essa parte depende de como você estruturou as subpastas e como as imagem são nomeadas
        

    return render(request, 'detalhe_animal.html', {'animal': animal, 'imagem': imagem})

def cadastro_pessoa(request):
    return HttpResponse("<h1>ABRIGO DE ANIMAIS ! TESTE DE VIEW 'cadastro_pessoa'</h1>")


def gestao_doacao(request):
    return HttpResponse("<h1>ABRIGO DE ANIMAIS ! TESTE DE VIEW 'gestao_doacao'</h1>")



def cadastro_animal(request):
    if request.method == 'POST':
        form_animal = FormCadastroAnimal(request.POST, request.FILES)
        animal_imagem = request.FILES.getlist('animal_imagem')

        if form_animal.is_valid():
            animal = form_animal.save(commit=False)  # Não salva ainda

           # Deixar os campos de nome e raça em minúsculo
            animal.nome = animal.nome.lower()
            animal.save()  # Salve o animal primeiro para gerar o ID

            # Salvar a data de criação
            data_criacao = timezone.now()
            data_formatada = data_criacao.strftime('%Y%m%d')  # Formato: YYYYMMDD

            # Criar o caminho da nova pasta
            nome_pasta = f"{animal.nome}"
            caminho_pasta = os.path.join(settings.MEDIA_ROOT, 'galeria', nome_pasta)
            os.makedirs(caminho_pasta, exist_ok=True)  # Cria a pasta se não existir

             # Salva as imagens
            for i, imagem in enumerate(animal_imagem):
                # Novo nome do arquivo com o nome do animal e data de criação (e índice para evitar conflito)
                novo_nome_arquivo = f"{animal.nome}_{data_formatada}_{i+1}.jpg"

                # Cria uma instância de FileSystemStorage para salvar no caminho da nova pasta
                fs = FileSystemStorage(location=caminho_pasta)

                # Salva a imagem no novo diretório com o nome ajustado
                caminho_imagem_salva = fs.save(novo_nome_arquivo, imagem)

                # Salva a referência da imagem no banco de dados
                GaleriaAnimal.objects.create(
                    animal=animal, 
                    imagem=os.path.join('galeria', nome_pasta, novo_nome_arquivo)
                )

            # Define sucesso como True
            contexto = {
                'form_animal': FormCadastroAnimal(),  # Reseta o formulário após o envio
                'sucesso': True
            }
            return render(request, 'cadastro_pet.html', contexto)
        else:
            contexto = {
                'form_animal': form_animal,
                'error': 'Erro ao cadastrar animal. Verifique os dados informados.'
            }
            return render(request, 'cadastro_pet.html', contexto)
    
    else:
        form_animal = FormCadastroAnimal()
        return render(request, 'cadastro_pet.html', {'form_animal': form_animal})

                                                             

site_abrigo/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Abrigo de Animais</title>

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- CSS do Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- JavaScript do Bootstrap e dependências (popper.js) -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

</head>

<body class="bg-light">
  <header>
      {% include "nav.html" %}
  </header>
  
  <main class="container">
      {% block content %} 
      {% endblock %}
  </main>
  
  <footer>
      {% include "footer.html" %}
  </footer>

{% block scripts %}
<!-- Carregar CSS do Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">

<!-- Carregar jQuery (necessário para o carousel do Bootstrap 5 funcionar) -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Carregar JS do Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}


</body>

</html>

site_abrigo/templates/cadastro_animal.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}


{% block content %}

<div class="container mx-auto p-4">
    <div class="d-grid gap-2 d-md-block">
        <h1>Cadastrar animal</h1>
        {% if sucesso %}
        <div class="alert alert-success" role="alert">
            Animal cadastrado com sucesso!
        </div>
        {% endif %}
        
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{ error }}
        </div>
        {% endif %}
    
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
    
            {% bootstrap_form form %}
            
        </form>

    
        <div class="d-grid gap-2 d-md-block mt-4" role="group">
            <button type="submit" class="btn btn-primary rounded">Cadastrar</button>
            <button type="reset" name="submit" class="btn btn-primary rounded ">Limpar</button>
        </div>
    </div>
</div>
{% endblock %}

site_abrigo/templates/detalhe_animal.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

{% block content %}

<div class="container-fluid p-4  d-flex flex-column min-vh-100">

    <h1 class="display-6">Detalhes do bichinho</h1>
    <div class="card mt-4" style="max-width: 100%;">
        <div class=" card-body">
    
            <div class="row g-2">
                <!-- Coluna para a imagem -->
                <div class="col-md-4">
                    {% if animal.imagem %}
                    <img src="{{ animal.imagem.url }}" alt="Imagem de {{ animal.nome }}" class="img-fluid rounded"
                        style="height: 100%; object-fit: cover;">
                    {% else %}
                    <img src="{% static 'img/imagem_default.jpg' %}" alt="Imagem padrão" class="img-fluid rounded"
                        style="height: 100%; object-fit: cover;">
                    {% endif %}
                </div>
    
                <!-- Coluna para os detalhes -->
                <div class="col-md-8">
                    <h5 class="card-title">Nome (Apelido): <span class="fs-4"><strong>{{ animal.nome|capfirst }}</strong></span></h5>
                    <p class="card-text"><strong>Idade:</strong> {{ animal.idade }} anos</p>
                    <p class="card-text"><strong>Raça:</strong> {{ animal.raca|capfirst }}</p>
                    <p class="card-text"><strong>Sexo:</strong> {{ animal.sexo }}</p>
                    <p class="card-text"><strong>Espécie:</strong> {{ animal.especie }}</p>
                    <!-- Botão ao final -->
                    <div class="mt-4">
                        <a href="#" class="btn btn-primary">Adotar {{ animal.nome|capfirst }}</a>
                    </div>
    
                </div>
                
            </div>
        </div>
        <div class="card-footer">
            <p class="card-text"><small class="text-muted">Criado em: {{ animal.data_criacao|date:"d/m/Y" }}</small>
            </p>
        </div>        
    </div>

    <h1>Galeria de fotos</h1>
        
        {% for item in animal.galeria.all %}
        {{ item }}
        <img src="{{ item.imagem.url }}" alt="Imagem de {{ item.titulo }}" class="img-fluid rounded"
        style="height: 100%; object-fit: cover;">

        {% endfor %}
</div>




{% endblock %}

site_abrigo/templates/footer.html
{% load bootstrap5 %}
    {% bootstrap_css %}

<footer class="bg-body-tertiary text-center text-lg-start mt-8">
        <div class="text-center p-4 " style="background-color: rgba(0, 0, 0, 0.05);">
            © 2024 Copyright <br> <a class="text-body" href="#">Andichii Dev</a>
        </div>
 
</footer>

site_abrigo/templates/home.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}

{% block content %}
<style>
    .custom-caption {
        background-color: rgba(0, 0, 0, 0.5);
        /* Fundo semi-transparente */
        padding: 15px;
        border-radius: 10px;
        width: auto;
        /* Ajusta o fundo ao tamanho do texto */
        display: inline-block;
        /* Faz com que o fundo envolva apenas o texto */
    }
</style>

<div class="d-flex flex-column min-vh-100">
    <!-- Hero Section (Carousel) -->
    <div class="flex-grow-1">
        <div class="container-fluid px-0">

            <div class="container mt-5">
                <h1 class="text-center m-4">Bem-vindos ao Abrigo Animal</h1>

            </div>

            <!-- Carrossel -->
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                    {% for animal in animais %}
                    <button type="button" data-bs-target="#carouselExampleIndicators"
                        data-bs-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"
                        aria-current="true" aria-label="Slide {{ forloop.counter }}"></button>
                    {% endfor %}
                </div>
                <div class="carousel-inner">
                    {% for animal in animais %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        {% if animal.imagem %}
                        <img src="{{ animal.imagem.url }}" class="d-block w-100" alt="Imagem de {{ animal.nome }}"
                            style="height: 60vh; object-fit: cover;">
                        {% else %}
                        <img src="{% static 'img/imagem_default.jpg' %}" class="d-block w-100" alt="Imagem padrão"
                            style="height: 60vh; object-fit: cover;">
                        {% endif %}
                        <div class="carousel-caption d-none d-md-block custom-caption">
                            <h5>{{ animal.nome }}</h5>
                        </div>
                    </div>
                    {% endfor %}
           
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>

        </div>
        <div class="container mt-5">
            <h2 class="text-center m-5">Adote. Não Compre.</h2>

        </div>

        {% include "lista_animais.html" %}
    </div>

</div>
{% endblock %}

site_abrigo/templates/lista_animais.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}



{% block content %}

<div class="container my-4">
    <h1 class="text-center mb-4">Lista de Animais Cadastrados</h1>

    <div class="row g-4">
        {% for animal in animais %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100">
                {% if animal.imagem %}
                <img src="{{ animal.imagem.url }}" class="card-img-top" alt="Imagem de {{ animal.nome }}" style="height: 200px; object-fit: cover;">
                {% else %}
                <img src="{% static 'img/imagem_default.jpg' %}" class="card-img-top" alt="Imagem de {{ animal.nome }}" style="height: 150px; object-fit: cover;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title display-6">{{ animal.nome|capfirst }}</h5>
                    <p class="card-text">{{ animal.idade }} anos | {{ animal.raca|capfirst }} | {{ animal.sexo }}</p>
                    {% if animal.disponivel_para_adocao%}
                    <p class="text-success fw-bold">Disponível para adoção</p>
                    {% else %}
                    <p class="text-danger fw-bold">Não disponível para adoção</p>
                    {% endif %}
                   
                    <a href="{% url 'detalhe_animal' animal.id %}" class="btn btn-outline-primary w-100">Ver mais detalhes</a>
                </div>
                
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

site_abrigo/templates/nav.html
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Abrigo Animal</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cadastro_animal' %}">Cadastro Animais</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'app_usuarios:cadastro_pessoa' %}">Cadastro Pessoa</a>
        </li>
        <li class="nav-item text-right">
          <a class="nav-link" href="/admin">Login admin</a>
        </li>

      </ul>

      <!-- #pesquisar animal por palavra chave -->
    <form class="d-flex" action="{% url 'pesquisar_animais' %}">
      <input
         class="form-control me-2"
         type="search"
         placeholder="Pesquisar animal"
         aria-label="Pesquisar"
         name="pesquisa_query"
      >
      <button class="btn btn-outline-secondary" type="submit">Search</button>
     </form>

    </div>
  </div>
</nav>

site_abrigo/templates/pesquisar_animais.html
{% extends 'base.html' %}

{% load bootstrap5 %}
{% load static %}

{% block content %}

<div class="d-flex flex-column min-vh-100">
    {% if pesquisa_query %}
    <div class="mt-5">
        <div class="text-center">
            <h1 class="display-6">Você pesquisou... <strong>{{ pesquisa_query|capfirst }}</strong></h1>
        </div>
        <hr>

        <div class="row g-4 justify-content-center">
            {% for animal in animais %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card h-100">
                    {% if animal.imagem %}
                    <img src="{{ animal.imagem.url }}" class="card-img-top" alt="Imagem de {{ animal.nome }}" style="height: 200px; object-fit: cover;">
                    {% else %}
                    <img src="{% static 'img/imagem_default.jpg' %}" class="card-img-top" alt="Imagem de {{ animal.nome }}" style="height: 200px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title display-6">{{ animal.nome|capfirst }}</h5>
                        <p class="card-text">{{ animal.idade }} anos | {{ animal.raca|capfirst }} | {{ animal.get_sexo_display }}</p>
                        {% if animal.disponivel_para_adocao %}
                        <p class="text-success fw-bold">Disponível para adoção</p>
                        {% else %}
                        <p class="text-danger fw-bold">Não disponível para adoção</p>
                        {% endif %}
                        <a href="{% url 'detalhe_animal' animal.id %}" class="btn btn-outline-primary w-100">Ver mais detalhes</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    {% else %}
    <div class="d-flex flex-column justify-content-center align-items-center min-vh-100 text-center">
        <h1 class="display-6">Desculpe... <br>Você precisa pesquisar um animal antes!</h1>
        <div>
            <img src="{% static 'img/img_cachorro_pesquisaelse.png' %}" alt="Imagem de cachorro" class="img-fluid" style="max-width: 400px;">
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}